version: '3'

services:
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: horsetrader
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: MFERiv6jojI
            MYSQL_ROOT_HOST: "%"
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db