# Generated by Django 2.0 on 2017-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('breed', models.CharField(choices=[('Arabian', 'Arabian'), ('Quarter Horse', 'Quarter Horse'), ('Thoroughbred', 'Thoroughbred'), ('Appaloosa', 'Appaloosa')], default='Arabian', max_length=255, verbose_name='Breed')),
                ('listing_date', models.DateTimeField(auto_now_add=True, verbose_name='Listing Date')),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=8, verbose_name='Price')),
            ],
        ),
    ]
